name: Makefile CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Pre-requisites
      run: ./md2html/scripts/pre-requisites.sh
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      shell: bash
      run: |
        export OPT_ARGS=-s
        make build
    - name: Check
      shell: bash
      run: |
        test -f out/DBS_CV_remote.pdf
        test -f out/index.html
